# Generated by Django 4.1.6 on 2023-03-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='icon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.images'),
        ),
    ]
