# Generated by Django 4.1.6 on 2023-02-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
