# Generated by Django 4.1.6 on 2023-02-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_created_date_teacher_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
