# Generated by Django 4.1.6 on 2023-02-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_classroom_createdbyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='updatedTimeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updatedTimeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updatedTimeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
