# Generated by Django 4.1.6 on 2023-02-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_rename_created_at_teacher_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='createdTimeStamp',
        ),
    ]
