# Generated by Django 4.1.6 on 2023-03-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_teacher_name_alter_teacher_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
