# Generated by Django 4.1.6 on 2023-04-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_remove_question_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='auth_type',
            field=models.CharField(choices=[('s', 'Secret Word'), ('i', 'Image'), ('n', 'Self')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='login_type',
            field=models.CharField(choices=[('s', 'Secret Word'), ('i', 'Image'), ('n', 'Self')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='adminpanel.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='adminpanel.task'),
        ),
    ]
