# Generated by Django 4.1.6 on 2023-02-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_classroom_id_alter_mes_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='shcool_id',
            new_name='school_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='shcool_id',
            new_name='school_id',
        ),
    ]
