# Generated by Django 4.1.6 on 2023-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_rename_updatedtimestamp_admin_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
