# Generated by Django 4.1.6 on 2023-02-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_admin_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answeredBy',
            new_name='answered_by',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='createdTimeStamp',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='updatedTimeStamp',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='createdById',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='createdTimeStamp',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='updatedTimeStamp',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='createdTimeStamp',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='updatedTimeStamp',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='createdTimeStamp',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='updatedTimeStamp',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='school_id',
        ),
        migrations.AddField(
            model_name='question',
            name='text_answer',
            field=models.TextField(default='No Text', null=True),
        ),
    ]
