# Generated by Django 4.1.6 on 2023-02-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_rename_answeredby_answer_answered_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='loginTimeStamp',
            new_name='login_date',
        ),
    ]
